company:
  name: "주식회사 로잉프로"
  representative: "김정겸"
  address: "경기도 하남시 덕풍동로 111-21, 케이앤몰동 10층 1021호"
  phone: "1566-1931"
  email: "contact@rowingpro.co.kr"
  businessNumber: "211-88-99912"
  corporateNumber: "110111-5216282"
  founded: "2013.08.29"
